
with open(r"E:\juhuo\cleanup_daily.py", "a", encoding="utf-8") as fh:
    fh.write("\n")
    fh.write("def c5(dry=True):\n")
    fh.write('    d = WS / "workspaces"\n')
    fh.write("    if not d.exists(): return 0, 0\n")
    fh.write("    n = s = 0\n")
    fh.write('    ap = ["*_article_text*","*_article_content*","*_text.txt","*_content.txt","*_raw.txt","*_scrape*.txt","*_crawl*.txt","*.article","*.scraped"]\n')
    fh.write("    for wd in d.iterdir():\n")
    fh.write("        if not wd.is_dir(): continue\n")
    fh.write("        for pt in ap:\n")
    fh.write("            for f in wd.rglob(pt):\n")
    fh.write("                if f.is_file():\n")
    fh.write("                    if dry: log(f'  [DRY] junk: {rp(f,d)}'): continue\n")
    fh.write("                    f.unlink()\n")
    fh.write("                    log(f'  DEL junk: {rp(f,d)}')\n")
    fh.write("                    n += 1; s += gs(f)\n")
    fh.write('    co = datetime.now() - timedelta(days=60)\n')
    fh.write('    cr = datetime.now() - timedelta(days=30)\n')
    fh.write("    for wd in d.iterdir():\n")
    fh.write('        ld = wd / "learning"\n')
    fh.write("        if not ld.exists(): continue\n")
    fh.write("        for f in ld.rglob('*'):\n")
    fh.write("            if not f.is_file(): continue\n")
    fh.write("            try:\n")
    fh.write("                mt = datetime.fromtimestamp(f.stat().st_mtime)\n")
    fh.write("                at = datetime.fromtimestamp(f.stat().st_atime)\n")
    fh.write("                if mt < co and at < cr:\n")
    fh.write("                    if dry: log(f'  [DRY] old learning: {rp(f,d)}'): continue\n")
    fh.write("                    f.unlink()\n")
    fh.write("                    log(f'  DEL old learning: {rp(f,d)}')\n")
    fh.write("                    n += 1; s += gs(f)\n")
    fh.write("            except: pass\n")
    fh.write("    seen = {}\n")
    fh.write("    for wd in d.iterdir():\n")
    fh.write('        md = wd / "memory"\n')
    fh.write("        if not md.exists(): continue\n")
    fh.write("        for f in md.glob('*.md'):\n")
    fh.write("            if not f.is_file(): continue\n")
    fh.write("            try:\n")
    fh.write("                base = f.stem\n")
    fh.write("                mt = datetime.fromtimestamp(f.stat().st_mtime)\n")
    fh.write("                if base in seen:\n")
    fh.write("                    op, om = seen[base]\n")
    fh.write("                    if mt > om:\n")
    fh.write("                        if dry: log(f'  [DRY] dup: {op.name} (keep {f.name})'): continue\n")
    fh.write("                        op.unlink()\n")
    fh.write("                        log(f'  DEL dup: {op.name} (keep {f.name})')\n")
    fh.write("                        n += 1; s += gs(op)\n")
    fh.write("                        seen[base] = (f, mt)\n")
    fh.write("                else:\n")
    fh.write("                    seen[base] = (f, mt)\n")
    fh.write("            except: pass\n")
    fh.write("    for wd in d.iterdir():\n")
    fh.write("        if not wd.is_dir(): continue\n")
    fh.write("        for td in wd.rglob('temp*"')
    fh.write("'):\n")
    fh.write("            if td.is_dir():\n")
    fh.write("                try:\n")
    fh.write("                    if not any(td.iterdir()):\n")
    fh.write("                        if dry: log(f'  [DRY] empty dir: {rp(td,d)}'): continue\n")
    fh.write("                        td.rmdir()\n")
    fh.write("                        log(f'  DEL empty dir: {rp(td,d)}')\n")
    fh.write("                        n += 1\n")
    fh.write("                except: pass\n")
    fh.write("    return n, s\n")
print("c5 written")
